# -*- coding: utf-8 -*-
"""permutation_combination.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jIV1CDCZ-hZ_qEmHSITtAH3gbvTcqz5H
"""

def factorial(number):
  """
  Factorial
  ---------
  A function that takes as argument an integer.
  return the factorial of positive numbers.
  """
  if number < 0:
    return 0
  elif number == 0:
    return 1
  else:
    return number * factorial(number - 1)

factorial(-1)

def permutation_combination(numb_el, numb_pl):
  """
  permitation_combination
  -----------------------
  A function that take as argument the number of element and the number of 
  possible places.
  ;return: the number of permutations and combinations.
  """
  permutations = 0
  combinations = 0
  if (numb_el < numb_pl or numb_el < 0 or numb_pl < 0):
    return (0, 0)
  permutations = (factorial(numb_el)/factorial(numb_el - numb_pl))
  combinations = permutations / factorial(numb_pl)
  return permutations, combinations

print(permutation_combination(10, 3))

print(permutation_combination(15, 1))

print(permutation_combination(15, 5))

print(permutation_combination(7, 3))